import { Page } from "../src/components/layout/Page";

const Home = () => (
  <Page>
    <h2>Test</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum sed tortor sit amet facilisis. Aenean tristique sapien elit, in hendrerit leo hendrerit id. Mauris elit ex, rhoncus rhoncus pretium a, dignissim in erat. Nullam condimentum mi quis dolor laoreet, id scelerisque enim euismod. Curabitur dictum vel magna sed mollis. Pellentesque quis est enim. Nullam non pulvinar urna. Aenean feugiat blandit consectetur. In ut nibh posuere, ornare tortor at, elementum tortor. Nullam molestie lectus neque, vitae pretium libero fringilla a. Proin ornare, orci et rutrum venenatis, justo ante elementum nulla, id rutrum nulla ligula tincidunt leo. Phasellus sed turpis nec ligula varius vestibulum non et arcu. Suspendisse porttitor auctor risus, a elementum neque efficitur at. Fusce a lacus ac urna tempus iaculis. Duis condimentum posuere suscipit.</p>
    <p>Proin sit amet porta tellus. Suspendisse ac ipsum dolor. Pellentesque aliquet molestie tincidunt. In hac habitasse platea dictumst. Vestibulum eget purus dapibus, sollicitudin massa a, placerat nunc. Fusce ullamcorper orci id convallis dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
    <p>Sed vel felis et magna lacinia malesuada vitae at quam. Duis at arcu in lacus pharetra maximus quis ut ex. Proin fermentum lacinia mi, nec tempor eros rhoncus vitae. Vestibulum cursus cursus ante, et finibus nisl bibendum sit amet. Etiam tempus mi vel ex varius iaculis. Aenean iaculis, tellus porta egestas ornare, est magna dapibus felis, et aliquam odio tellus quis tellus. Nullam eu nulla in mauris vehicula egestas. In tincidunt tortor ut sapien semper, sed vestibulum mauris sagittis.</p>
    <p>In in ex nec sem semper posuere. Sed suscipit mauris eu ultricies auctor. Curabitur augue ipsum, feugiat at arcu nec, semper laoreet ipsum. Pellentesque sit amet est massa. Nullam vitae massa sit amet sapien egestas gravida. Vestibulum congue quam eu nisi tempus, non dictum purus feugiat. Curabitur nisi nisl, vehicula viverra placerat nec, sagittis eget lacus. Morbi id dolor non erat tempor luctus. Ut scelerisque ante metus, id sollicitudin lectus fermentum sit amet. Mauris fermentum semper metus, et pharetra risus cursus sit amet. Nulla consectetur varius congue. Nullam egestas egestas tortor, nec congue felis vestibulum ac. Mauris sagittis, tortor vel mattis congue, nisl lectus gravida lectus, ut suscipit urna augue eget sem. Etiam sed ultricies quam.</p>
    <p>Quisque turpis metus, rutrum ut finibus at, consectetur a sem. Morbi nec dignissim nulla. Phasellus lacinia gravida enim, id venenatis ipsum varius ut. Vestibulum egestas fringilla lorem, sed luctus nisi dapibus euismod. Suspendisse commodo sit amet sapien at vehicula. Vestibulum vitae arcu vel dui posuere sollicitudin a non orci. Suspendisse et tempor ante, et mattis risus. Vestibulum non arcu semper, finibus ipsum in, sodales mi. Cras dolor nunc, egestas at malesuada vitae, luctus id metus. Donec luctus odio vitae efficitur tristique. Etiam vestibulum diam quam, ut pellentesque elit varius eget.</p>
    <p>Integer eu sem id eros condimentum dictum. Curabitur pretium sapien quis urna bibendum, nec fermentum sapien sagittis. Integer porttitor, enim ac aliquam molestie, diam tellus cursus neque, eu malesuada turpis leo sed mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent eu pharetra nunc. Duis euismod, eros a tristique efficitur, odio libero malesuada sapien, quis tempor erat ipsum et erat. Sed mollis ultricies urna, id convallis lectus semper rutrum.</p>
    <p>Praesent diam nisl, tincidunt quis vehicula ut, lobortis ut quam. Vivamus vel diam non metus euismod dignissim. Vivamus facilisis pulvinar lorem eget auctor. Cras commodo turpis eu metus semper rutrum. Fusce tristique sit amet sem pulvinar auctor. Sed sagittis id purus vitae elementum. Etiam viverra, dolor ut tempus porttitor, ipsum velit accumsan quam, a egestas nunc justo in arcu. Sed nec erat consequat, tempus ex eget, efficitur nisi. In efficitur eget orci eu tempus. Donec molestie dapibus lectus blandit dignissim. Maecenas malesuada massa commodo scelerisque tincidunt. Vestibulum lacinia pulvinar mi, venenatis venenatis nulla porttitor at. Pellentesque et convallis sapien, ac cursus sem. Ut sodales eros in enim feugiat, a lobortis libero molestie. Sed porttitor et tortor non iaculis. Duis sollicitudin in nisl vel hendrerit.</p>
    <p>Sed eget ultrices mi. Ut vestibulum elit ligula, ac lacinia nisl malesuada consequat. Vestibulum ultrices sapien et suscipit bibendum. Donec odio diam, iaculis at mattis sed, interdum nec turpis. Morbi lorem purus, imperdiet et hendrerit sed, egestas sit amet tortor. Quisque at rutrum enim. Ut rutrum pretium tristique. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam nisl orci, egestas vel facilisis id, posuere ac nibh.</p>
    <p>Sed a nisl ac ipsum placerat ullamcorper. Aliquam hendrerit porttitor leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla quis lorem quis urna malesuada accumsan. Sed tristique tincidunt elit non laoreet. Nulla nec vehicula arcu. Maecenas condimentum enim sed dapibus vestibulum. Maecenas faucibus tincidunt enim vitae varius. Proin molestie est libero, quis consequat urna vulputate in. Nulla eget viverra nisi. Pellentesque nec placerat mauris. Morbi laoreet ipsum sed libero ullamcorper sodales. Pellentesque lorem ligula, rhoncus vel dolor quis, scelerisque volutpat massa.</p>
    <p>Integer aliquam at tellus et dignissim. Ut sit amet ornare mi, at vestibulum sem. In vitae nibh vulputate, posuere felis quis, consequat erat. Donec ante tellus, ornare non luctus ac, dapibus nec quam. Morbi et lacus sapien. Nullam nec fringilla enim. Morbi mattis nunc non dolor sollicitudin, quis euismod metus egestas. Vestibulum nec dictum sem. Integer venenatis velit ipsum, ac ullamcorper nibh maximus non. Suspendisse eget sem mi. Donec interdum purus sit amet dui consequat suscipit. Integer elementum tellus a lectus lobortis facilisis. Nam sed sem pretium justo condimentum hendrerit. Ut accumsan felis id dolor tristique, ut porta arcu dapibus. Pellentesque est ligula, auctor in auctor vel, faucibus vel tortor. Donec ut blandit arcu, bibendum fringilla elit.</p>
  </Page>
);


export default Home;